### ISSUE TITLE
What about a no_std variant (for use on Microcontrollers)

### ISSUE THREAD

**Issue by uwearzt** [Klapeyron/rtps-rs#14]
Do you think that is feasible? Maybe we would have to factor out the Tokio support and use something like smoltcp directly...

**Comment by Klapeyron** [comment]
I think that for now we will stay focused on scalability and correctness regarding the specification. If it will be possible to reduce number of std dependencies in the future, then of course I think that it is good proposition. In case of TCP stack, for sure we need some possibility to send and receive UDP packages over uni/multicast.
