### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by piotr-maks** [Klapeyron/rtps-rs#19]
Hi,

Have you considered enabling [Dependabot Preview](https://github.com/marketplace/dependabot-preview) for this repository? I found it recently and it looks much more mature and robust than handcrafted GitHub Action that I have created PR for  #18. It can update dependencies in Cargo.toml and Cargo.lock
I have already check it and it looks promising: 
https://github.com/piotr-maks/rtps-rs/pull/7 
https://github.com/piotr-maks/rtps-rs/pull/6

**Comment by Klapeyron** [comment]
Hiho,
looks good! I have reverted previous auto update feature and enabled this app, let's see how it will work :)
Thanks!
