### ISSUE TITLE
Time to make a new release?

### ISSUE THREAD

**Issue by ckaran** [Klapeyron/rtps-rs#45]
I can see that this project is under active development, but the [latest release on crates.io](https://crates.io/crates/rtps-rs) is two years old.  Is it time for a new release?

**Comment by Klapeyron** [comment]
Hi,
yep, I have "resurrected" it few days ago after quite long break. Thanks for the reminder, here is also a new tag [0.1.2](https://github.com/Klapeyron/rtps-rs/releases/tag/0.1.2) :)

**Comment by ckaran** [comment]
Thank you!
