### ISSUE TITLE
Add text to README.md

### ISSUE THREAD

**Issue by frehberg** [Klapeyron/rtps-rs#9]
The README.md should state 
* What is RTPS
* Roadmap
etc.

**Comment by frehberg** [comment]
This is a first sketch of the text for README.md, still containing a number of placeholders to be filled. Please feel free to comment.

**Comment by Klapeyron** [comment]
Hello,
thanks for contribution :). Yep, good point, for now we haven't time to write README... In case of the the roadmap, we will probably migrate in April to GitLab (due end of the licence there) and use their features.

**Comment by Klapeyron** [comment]
Merged :), thanks again for PR!
